merge:
  whitelist:
    # a PR must have these labels set
    labels: ["dependencies","depfu"]
  blacklist:
    # a PR may not have these labels set
    labels: ["wip"]
  # merge method, see https://help.github.com/en/articles/about-merge-methods-on-github
  # one of: merge, squash, rebase
  method: rebase
  # status checks required in addition to the ones defined in GitHub Branch 
  delete_after_merge: true
